### ISSUE TITLE
Showing Red Cross after burning the firmware

### ISSUE THREAD

**Issue by pushkar-bharambe** [BPI-STEAM/BPI-BIT-Webduino#2]
I burned the Webduino firmware to Bpi:bit board with the esp flash tool. But after booting it just showing a red cross and is not creating any wifi network!

**Comment by yelvlab** [comment]
You need to hold down the A button and power on when the power is off to enter the normal user interface.

**Comment by pushkar-bharambe** [comment]
Thank You very much! Got it working right!

**Comment by yelvlab** [comment]
I will close it.

**Comment by yelvlab** [comment]
anything else?

**Comment by pushkar-bharambe** [comment]
No
